manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.1.0
      import:
        # Limit the Zephyr modules to the required set
        name-allowlist:
          - hal_espressif
          - mbedtls
          - mcuboot

    - name: memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      # Temporarily use a fork with ESP32 support, until 1.26.0 is released
      revision: noahp/1.25.0+esp32-support
