manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.6.0
      import:
        # Limit the Zephyr modules to the required set
        name-allowlist:
          - hal_espressif
          - mbedtls
          - mcuboot

    - name: memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: 1.10.1
