# Settings for Zephyr >= 4.5

# Carry over from v4.4
CONFIG_MBEDTLS_CIPHERSUITE_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256=y
CONFIG_MBEDTLS_SSL_SERVER_NAME_INDICATION=y

# Split from CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN in Zephyr v4.5
CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=4096
CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096
