# Settings for Zephyr >= 4.5

CONFIG_MBEDTLS_SSL_SERVER_NAME_INDICATION=y

# Split from CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN in Zephyr v4.5
CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=4096
CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096
