# Settings for Zephyr < 4.4

CONFIG_MBEDTLS_SERVER_NAME_INDICATION=y

CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=4096

# PSA Crypto prevents establishing a TLS connection with Memfault on pre-4.4
# Zephyr; use MbedTLS legacy crypto instead.
CONFIG_MBEDTLS_USE_PSA_CRYPTO=n
CONFIG_MBEDTLS_SHA1=y
