name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        board: [esp32c3_devkitm, esp32s3_devkitm]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zephyr-esp32-example

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-esp32-example
          toolchains: xtensa-espressif_esp32s3_zephyr-elf riscv64-zephyr-elf

      - name: 💾 Cache ~/.cache/ccache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ccache
          key: ccache-v1-${{ runner.os }}-${{ hashFiles('zephyr-workspace/zephyr-esp32-example/west.yml') }}
          restore-keys: |
            ccache-v1-${{ runner.os }}-

      - name: Run twister
        run: |
          # not part of action-zephyr-setup
          west blobs fetch hal_espressif

          zephyr/scripts/twister
          --platform ${{ matrix.board }}
          --testsuite-root zephyr-esp32-example

          ccache -sv

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: twister-artifacts
          path: |
            twister-out/**/*.log
