name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # Project setup dominates vs. actual per-configuration build times, so
    # just run twister for all boards instead of splitting into separate jobs.
    # strategy:
    #   matrix:
    #     board:
    #       [
    #         esp_wrover_kit/esp32/procpu,
    #         esp32s3_devkitm/esp32s3/procpu,
    #         esp32s3_devkitc/esp32s3/procpu,
    #         esp32c3_devkitm,
    #       ]
    runs-on: ubuntu-latest
    steps:
      - name: ☑️ Checkout
        uses: actions/checkout@v4
        with:
          path: zephyr-esp32-example

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: ♻️ Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-esp32-example
          toolchains: riscv64-zephyr-elf:xtensa-espressif_esp32_zephyr-elf:xtensa-espressif_esp32s3_zephyr-elf

      - name: 💾 Cache ~/.cache/ccache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ccache
          key: ccache-v1-${{ runner.os }}-${{ hashFiles('zephyr-workspace/zephyr-esp32-example/west.yml') }}
          restore-keys: |
            ccache-v1-${{ runner.os }}-

      - name: 🌪️ Run twister
        run: |
          # not part of action-zephyr-setup
          west blobs fetch hal_espressif

          zephyr/scripts/twister --testsuite-root zephyr-esp32-example

          ccache -sv

      - name: 🎨 Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: twister-artifacts
          path: |
            twister-out/**/*.log
